import React from "react";

export const icons = {
  loader: (
    <svg
      className="svg_loader"
      xmlns="http://www.w3.org/2000/svg"
      style={{ margin: "auto", display: "block", shapeRendering: "auto" }}
      width="256px"
      height="256px"
      viewBox="0 0 100 100"
      preserveAspectRatio="xMidYMid"
    >
      <g transform="rotate(0 50 50)">
        <rect
          x="47"
          y="21.5"
          rx="3"
          ry="3"
          width="6"
          height="15"
          fill="#b5b1bf"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="1s"
            begin="-0.9s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
      <g transform="rotate(36 50 50)">
        <rect
          x="47"
          y="21.5"
          rx="3"
          ry="3"
          width="6"
          height="15"
          fill="#b5b1bf"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="1s"
            begin="-0.8s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
      <g transform="rotate(72 50 50)">
        <rect
          x="47"
          y="21.5"
          rx="3"
          ry="3"
          width="6"
          height="15"
          fill="#b5b1bf"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="1s"
            begin="-0.7s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
      <g transform="rotate(108 50 50)">
        <rect
          x="47"
          y="21.5"
          rx="3"
          ry="3"
          width="6"
          height="15"
          fill="#b5b1bf"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="1s"
            begin="-0.6s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
      <g transform="rotate(144 50 50)">
        <rect
          x="47"
          y="21.5"
          rx="3"
          ry="3"
          width="6"
          height="15"
          fill="#b5b1bf"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="1s"
            begin="-0.5s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
      <g transform="rotate(180 50 50)">
        <rect
          x="47"
          y="21.5"
          rx="3"
          ry="3"
          width="6"
          height="15"
          fill="#b5b1bf"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="1s"
            begin="-0.4s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
      <g transform="rotate(216 50 50)">
        <rect
          x="47"
          y="21.5"
          rx="3"
          ry="3"
          width="6"
          height="15"
          fill="#b5b1bf"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="1s"
            begin="-0.3s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
      <g transform="rotate(252 50 50)">
        <rect
          x="47"
          y="21.5"
          rx="3"
          ry="3"
          width="6"
          height="15"
          fill="#b5b1bf"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="1s"
            begin="-0.2s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
      <g transform="rotate(288 50 50)">
        <rect
          x="47"
          y="21.5"
          rx="3"
          ry="3"
          width="6"
          height="15"
          fill="#b5b1bf"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="1s"
            begin="-0.1s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
      <g transform="rotate(324 50 50)">
        <rect
          x="47"
          y="21.5"
          rx="3"
          ry="3"
          width="6"
          height="15"
          fill="#b5b1bf"
        >
          <animate
            attributeName="opacity"
            values="1;0"
            keyTimes="0;1"
            dur="1s"
            begin="0s"
            repeatCount="indefinite"
          ></animate>
        </rect>
      </g>
    </svg>
  ),
  star: (
    <svg
      className="svg_star"
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
    >
      <path d="M12 .587l3.668 7.568 8.332 1.151-6.064 5.828 1.48 8.279-7.416-3.967-7.417 3.967 1.481-8.279-6.064-5.828 8.332-1.151z" />
    </svg>
  ),
};
